//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinHue_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinHue_Core.Properties.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort scan.
        /// </summary>
        public static string DetectPairBridgeAbortScan {
            get {
                return ResourceManager.GetString("DetectPairBridgeAbortScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiKey.
        /// </summary>
        public static string DetectPairBridgeApiKey {
            get {
                return ResourceManager.GetString("DetectPairBridgeApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Version.
        /// </summary>
        public static string DetectPairBridgeApiVersion {
            get {
                return ResourceManager.GetString("DetectPairBridgeApiVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DetectPairBridgeDefault {
            get {
                return ResourceManager.GetString("DetectPairBridgeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect and Pair.
        /// </summary>
        public static string DetectPairBridgeDPBHeader {
            get {
                return ResourceManager.GetString("DetectPairBridgeDPBHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find my bridge.
        /// </summary>
        public static string DetectPairBridgeFindBridge {
            get {
                return ResourceManager.GetString("DetectPairBridgeFindBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Portal.
        /// </summary>
        public static string DetectPairBridgeFindPortal {
            get {
                return ResourceManager.GetString("DetectPairBridgeFindPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Right-click on the bridge list for context menu.
        /// </summary>
        public static string DetectPairBridgeHint {
            get {
                return ResourceManager.GetString("DetectPairBridgeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Info.
        /// </summary>
        public static string DetectPairBridgeInfo {
            get {
                return ResourceManager.GetString("DetectPairBridgeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string DetectPairBridgeIP {
            get {
                return ResourceManager.GetString("DetectPairBridgeIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC.
        /// </summary>
        public static string DetectPairBridgeMAC {
            get {
                return ResourceManager.GetString("DetectPairBridgeMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DetectPairBridgeName {
            get {
                return ResourceManager.GetString("DetectPairBridgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair.
        /// </summary>
        public static string DetectPairBridgePair {
            get {
                return ResourceManager.GetString("DetectPairBridgePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan aborted..
        /// </summary>
        public static string DetectPairBridgeScanAborted {
            get {
                return ResourceManager.GetString("DetectPairBridgeScanAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan complete..
        /// </summary>
        public static string DetectPairBridgeScanComplete {
            get {
                return ResourceManager.GetString("DetectPairBridgeScanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan IP.
        /// </summary>
        public static string DetectPairBridgeScanIp {
            get {
                return ResourceManager.GetString("DetectPairBridgeScanIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan IP Complete..
        /// </summary>
        public static string DetectPairBridgeScanIPComplete {
            get {
                return ResourceManager.GetString("DetectPairBridgeScanIPComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Portal Complete..
        /// </summary>
        public static string DetectPairBridgeScanPortalComplete {
            get {
                return ResourceManager.GetString("DetectPairBridgeScanPortalComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan UPNP Complete..
        /// </summary>
        public static string DetectPairBridgeScanUPNPComplete {
            get {
                return ResourceManager.GetString("DetectPairBridgeScanUPNPComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect and Pair Bridges....
        /// </summary>
        public static string DetectPairBridgeTitle {
            get {
                return ResourceManager.GetString("DetectPairBridgeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan UPNP.
        /// </summary>
        public static string DetectPairBridgeUpnp {
            get {
                return ResourceManager.GetString("DetectPairBridgeUpnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice : V1 (Round) Bridge not supported. (Will Not list here).
        /// </summary>
        public static string DetectPairBridgeWarning {
            get {
                return ResourceManager.GetString("DetectPairBridgeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string MainMenuApplication {
            get {
                return ResourceManager.GetString("MainMenuApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string MainMenuQuit {
            get {
                return ResourceManager.GetString("MainMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainMenuSettings {
            get {
                return ResourceManager.GetString("MainMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect and pair.
        /// </summary>
        public static string RibbonBridgePair {
            get {
                return ResourceManager.GetString("RibbonBridgePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge.
        /// </summary>
        public static string RibbonBridgePairing {
            get {
                return ResourceManager.GetString("RibbonBridgePairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Bridge.
        /// </summary>
        public static string RibbonBridgeSelected {
            get {
                return ResourceManager.GetString("RibbonBridgeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string RibbonBridgeSettings {
            get {
                return ResourceManager.GetString("RibbonBridgeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creators.
        /// </summary>
        public static string RibbonCreators {
            get {
                return ResourceManager.GetString("RibbonCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string RibbonHome {
            get {
                return ResourceManager.GetString("RibbonHome", resourceCulture);
            }
        }
    }
}
